### PR TITLE
[Fix] Update react native CLI to support white labeling with XCode 12

### PR DESCRIPTION
**Pull request by ljcp**
## Proposed changes
 update react-native CLI to v4.13.0 to fix executableFolderPath to run app name in iOS 14.0, needed for changing the product name - white labeling feature

## Issue(s)
https://github.com/react-native-community/cli/pull/1236	

## How to test or reproduce
1. With Xcode 12 change the Product Name to a custom one
2. yarn run ios

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] I have added necessary documentation (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by diegolmello** [comment]
AFAIK CLI is on `yarn.lock` just because some lib needs it.
You shouldn't be using it directly though.
Instead of running `react-native ...`, use `npx react-native ...` so you pick latest stable version.

**Comment by ljcp** [comment]
@diegolmello updating the yarn.lock is the official way of doing it as stated in the react native docs https://github.com/react-native-community/cli#updating-the-cli , without it npx react native will not pick the latest stable CLI

**Comment by diegolmello** [comment]
It's ugly, but it's on the docs, so I'm opening again.

**Review by diegolmello — APPROVED** [review]

**Comment by diegolmello** [comment]
@ljcp Merged. Thank you.

**Pull request merged**
