### PR TITLE
Add support for tasks and unordered list markdown 

### LINKED ISSUE #4927: Add support for tasks and unordered list markdown
### Description:
Tasks and unordered list does not appear in correct format as that in RC web app.

### Environment Information:

- Rocket.Chat Server Version: open.rocket.chat (6.0.0)

### Steps to reproduce:

1. Tasks should display in expected form
2. Unordered list should display in expected form 

### Expected behavior:
image

### Actual behavior:
WhatsApp Image 2023-02-27 at 17 22 36

### PR DESCRIPTION
**Pull request by imf-ali**
## Issue(s)	
Tasks and unordered list does not appear in correct format as that in RC web app.

## How to test or reproduce
- [x] Tasks should display in expected form
- [x] Unordered list should display in expected form

## Screenshots
Previous behaviour
image

Improvement
image

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

Fix #4927

### CODE REVIEW

**Comment by imf-ali** [comment]
Hey @diegolmello and @GleidsonDaniel, can you review this?

**Comment by imf-ali** [comment]
@diegolmello and @GleidsonDaniel, can you guys have a look at it?

**Review by diegolmello — CHANGES_REQUESTED** [review]
Thanks for your contribution!
Can you fix lint?

**Comment by imf-ali** [comment]
I have made the fix, kindly have a look @diegolmello.

**Comment by imf-ali** [comment]
@diegolmello can you please have a look at it?

**Comment by imf-ali** [comment]
Hey @diegolmello, please have a look at the PR.

**Pull request closed without merging**
