### PR TITLE
[FIX] Login and register via Google OAuth

### LINKED ISSUE #3644: [BUG] Google OAth not working on the android application
### Description:

Whenever the user triies to log into the Open Workspace Server using Google OAth, they are sent back to the login screen. The user is not authorized.  

 ### Environment Information:

- Rocket.Chat App Version: 4.23.0.27401
- Device Name: Redmi K20 Pro
- OS Version:  Android 10 QKQ1.190825.002

### Steps to reproduce:

1. Download and Open the android Application.
2. Click - Join Our Open Workspace 
3. Click on continue with Google 
4. Select your Google Account

### Expected behavior:

1. The application should authorize the user using the Gmail. 

### Actual behavior:

1. The user is sent back to the login screen. 

https://user-images.githubusercontent.com/70485812/150637302-59ce89aa-6802-46d7-a265-4dd939cee9a3.mp4

### PR DESCRIPTION
**Pull request by try-catch-stack**
## Proposed changes

Login or register using Google was not working and the user was redirected to the login page everytime trying to login via Google.

## Issue(s)	

Fixes #3644 

## How to test or reproduce

1) Login or register via Google and you'll be redirected to he login screen again. (Tried and tested on the open community server)

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [X] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by try-catch-stack** [comment]
@diegolmello @GleidsonDaniel The redirect uri was causing the issue. I do not know the other redirect uri (if any) other than the base, registered on the google console.
Can you please take a look if we have some other redirect uri or this is fine as it does solves the issue.

**Review by debdutdeb — APPROVED** [review]
@diegolmello the same happened with out openlms oauth couple days ago, can't find the thread sorry 🙈 best person to confirm this would be Marcelo.

**Comment by diegolmello** [comment]
Planned to be reviewed this sprint.

**Comment by reinaldonetof** [comment]
LGTM

**Comment by try-catch-stack** [comment]
Solved by https://github.com/RocketChat/Rocket.Chat/pull/24381

**Pull request closed without merging**
