### PR TITLE
using pure Expo. Add outside tabbar and can be used as a chat module …

### PR DESCRIPTION
**Pull request by ZackLeonardo**
1. using pure expo.
2. add outside TabBar and make this a chat module which can be used with other modules in an app.
Simulator Screen Shot - iPhone 6s - 2019-04-01 at 14 42 25
Simulator Screen Shot - iPhone 6s - 2019-04-01 at 14 42 47
Simulator Screen Shot - iPhone 6s - 2019-04-01 at 14 42 54

### CODE REVIEW

**Comment by diegolmello** [comment]
@ZackLeonardo Thanks for this PR. What are you aiming to do here?
What problem are you aiming to solve?

**Comment by ZackLeonardo** [comment]
@diegolmello Glad to hear your question. My aim is to make a PR not only IM(rocket.chat) but also can be used with other modules liking many apps need. And another aim is to use Expo in this PR to take advantage of this Hybrid framework. So it is not just solving any specific problem. Thx.

**Comment by ZackLeonardo** [comment]
@CLAassistant have signed. Thx.

**Comment by ZackLeonardo** [comment]
@diegolmello hello. this PR updates frequently: https://github.com/ZackLeonardo/react-native-chat. I will merge it later.

**Comment by diegolmello** [comment]
@ZackLeonardo Nice! What steps you made to use Expo? We use some native libs.

**Comment by ZackLeonardo** [comment]
@diegolmello I replaced those native libs. There are some pure Expo libs can be used. And I also write some using React Native libs. I appreciate Rocket.Chat very much and wanna study with u guys. Is there someway to accept this Expo PR? There are still lots of work to do. That is what I am doing and wanna make Rocket.Cha better and better together.

**Comment by diegolmello** [comment]
@ZackLeonardo

> I appreciate Rocket.Chat very much and wanna study with u guys.

You mean GSoC? You need to draft your proposal in your GSoC dashboard and get it reviewed until April 9th. Hurry up!

> Is there someway to accept this Expo PR?

We have no intention to support Expo. Sorry.

**Comment by ZackLeonardo** [comment]
@diegolmello Google Summer of Code? No. That is not what I mean. I will continue and forward. Thx anyway.

**Comment by ZackLeonardo** [comment]
@diegolmello I wanna know if it is possible to add this PR in README? So that if anyone wanna use Expo they can try this.

**Pull request closed without merging**
