### PR TITLE
[IMPROVEMENT] Add username on status messages

### LINKED ISSUE #1689: missing user name for status messages, like 'Has joined channel', 'Message removed' etc.
- Your Rocket.Chat Experimental app version: 4.4.0 (and 4.3.1 stable version)
- Your Rocket.Chat server version: 2.4.5
- Device (or Simulator) you're running with: OnePlus 7 Pro (Android 10.0.3)

It would be helpful if the user name was displayed in the status messages, such as 'Has joined channel', 'Message removed'. In their current form, the status messages are not very informative.

rc

### PR DESCRIPTION
**Pull request by dkoo761**
## Proposed changes

- Added username (or real name, depending on setting) to the start of the following message types:
  - message removed
  - message pinned
  - message snippeted
  - user joined channel
  - user joined discussion
  - user left channel
- Removed "vertical center" alignment so that the small avatar lines up better vertically with the top of the system message rather than the middle of the message (which looked bad on multi-line system messages).

## Issue(s)	

Closes #1689

## Screenshots

RCRN-1689

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dkoo761** [comment]
This is a replacement / improvement on a previous PR: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1708

**Comment by diegolmello** [comment]
@dkoo761 Awesome! We'll take a look on it soon. Thanks.

**Comment by dkoo761** [comment]
I don't think the 2 errors in the checks are related to my code

- detox-test-rooms error appears to be a flaky test run as I didn't get any errors when I ran the detox test suite locally.

- looks like the ios-build error is related to a fastlane issue in progress here: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2558

**Review by diegolmello — APPROVED** [review]
LGTM

**Pull request merged**
