### PR TITLE
chore: improve encrypted button on create discussion view

### LINKED ISSUE #5465: Switch not aligned properly with text "Encrypted" in CreateDiscussionView
### Description:

The text Encrpyted and Switch are not aligned properly

### Environment Information:

- Rocket.Chat Server Version: 6.6.0
- Rocket.Chat App Version: 4.44.0+
- Device Name: Realme 9
- OS Version: Android

### Steps to reproduce:

1. Go to Create New
2. Click on Discussion
3. Select a channel or group

### Expected behavior:

The title and Switch must align properly

### Actual behavior:

The title and Switch not align properly

### Additional context:

WhatsApp Image 2024-01-07 at 12 24 41 AM

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Proposed changes
Switch not aligned properly with text `Encrypted` in CreateDiscussionView

## Issue(s)	
Fixes #5465 

## How to test or reproduce

1. Go to Create New
2. Click on Discussion
3. Select a channel or group

## Screenshots
WhatsApp Image 2024-01-07 at 12 24 41 AM (1)

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by SanjaySargam** [comment]
Can any moderators please look at this PR

**Comment by GleidsonDaniel** [comment]
This needs to be validated with the product team, I will send it here on the channel and as soon as they respond I will give feedback.

**Comment by GleidsonDaniel** [comment]
Just remove the icon and the top and bottom borders.

**Comment by SanjaySargam** [comment]
WhatsApp Image 2024-01-20 at 2 22 29 PM

**Comment by SanjaySargam** [comment]
@GleidsonDaniel Made requested changes. Kindly review it. Thanks!

**Review by GleidsonDaniel — APPROVED** [review]

**Pull request merged**
