### PR TITLE
[FIX] Can't close the keyboard after entering data in one text box on the screen

### PR DESCRIPTION
**Pull request by reinaldonetof**
## Proposed changes

> I go to the "Room Info Edit" screen. Tap on the "Name" field - the keyboard appears and I enter the text. After entering the text, it is not possible to remove the keyboard - tap outside the input field does not remove it

## Issue(s)	

Closes https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3113
## How to test or reproduce

- Test the views:
- ProfileView
- RoomInfoEditView
- CreateDiscussionView
- CreateChannelView
- E2EEnterYourPasswordView
- ForgotPasswordView
- LoginView
- RegisterView
- WorkspaceView

#### Before
https://user-images.githubusercontent.com/47038980/218823805-91eaf11b-149e-4912-bc1e-d3474ac5aa6b.mp4

#### After
https://user-images.githubusercontent.com/47038980/218823789-6bfb025f-4dfa-483a-aa1f-0f601792b6e8.mp4

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

[TC-392]

[TC-392]: https://rocketchat.atlassian.net/browse/TC-392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by GleidsonDaniel — CHANGES_REQUESTED** [review]
If on android this is handled natively, why does this solution consider android?

**Comment by reinaldonetof** [comment]
> If on android this is handled natively, why does this solution consider android? I think the problem may be another one, but android handles it natively.
> 
> But I could be wrong... Anyway you have to validate on ios too.

Actually the error it's occurring on both! If you test on Android and iOS you will check the keyboard isn't dismissed when clicking outside the input.

**Comment by GleidsonDaniel** [comment]
I think you misunderstood my point...
On android it doesn't work because in this file here: `app/lib/methods/helpers/scrollPersistTaps.ts`
We are saying it to the keyboard, however changing it to `handled` will work.
The point is, shouldn't switching to handled be enough? Why are we using always?

We are solving a problem, but this problem was created by us putting `always` in this file.

**Comment by GleidsonDaniel** [comment]
Update your PR with develop and run detox on it to see if everything is working normally.

**Review by diegolmello — APPROVED** [review]

**Pull request merged**
