### PR TITLE
Removed toast

### LINKED ISSUE #836: Remove toast
https://github.com/remobile/react-native-toast is dead.

For now, let's show simple Alerts or even nothing.

### PR DESCRIPTION
**Pull request by pranavpandey1998official**
@RocketChat/ReactNative

Closes #836

ezgif com-video-to-gif

### CODE REVIEW

**Comment by diegolmello** [comment]
@pranavpandey1998official Nice job!
Can you try https://github.com/crazycodeboy/react-native-easy-toast and see if the results are reasonable?
Thanks.

**Comment by pranavpandey1998official** [comment]
I will do it after action-sheet is resolved as implementation right now of this requires code that is going to be deleted anyways

**Comment by diegolmello** [comment]
> I will do it after action-sheet is resolved as implementation right now of this requires code that is going to be deleted anyways

@pranavpandey1998official Fine. Thanks.

**Comment by pranavpandey1998official** [comment]
> Lint is failing

solved

**Pull request closed without merging**
