### PR TITLE
chore: migrate from react native animation api to react native reanimated api

### PR DESCRIPTION
**Pull request by jsathu07**
## Proposed changes

The react native reanimated library has become the standard for handling animations. This pull request transitions existing react native animation APIs to utilize reanimated

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jsathu07** [comment]
@diegolmello I want to migrate the files in the first commit. Can I work on this?

**Comment by diegolmello** [comment]
@jsathu07 Sure. Can you migrate them to function components first in a separate PR please?

**Comment by jsathu07** [comment]
Sure @diegolmello

**Comment by jsathu07** [comment]
> @jsathu07 Sure. Can you migrate them to function components first in a separate PR please?

@diegolmello I have done the changes in this pr. #5584

**Comment by diegolmello** [comment]
@jsathu07 Thanks! We're going to take a look asap.

**Comment by jsathu07** [comment]
Due to some errors I'm closing this PR and continuing the work on this PR #5623

**Pull request closed without merging**
