### PR TITLE
[FIX] Non-reply attachments displaying time

### LINKED ISSUE #2901: [BUG] Non-quote attachments use the inaccurate timestamp.
### Description:

Demonstrated on the Open.Rocket.Chat server quite often. In the general channel there, a lot of messages about GitHub activity are shown. However, they all share an origin time of 00:00:00 GMT 1st January 1970, which is to say they use the zero value for the timestamp.

This is unnecessary, as the timestamp is not supposed to be relevant in the message. In the Web Client, the timestamp is not rendered in the "default" attachment.

Screenshot_20210212-200448

### Environment Information:

- Rocket.Chat Server Version: Open.Rocket.Chat
- Rocket.Chat App Version: 4.14.1
- Device Name: Oneplus 6
- OS Version: Android 10

### Steps to reproduce:

1. Open General channel on Open.Rocket.Chat in web client and app.
2. In the web client, the Github messages do not have the time rendered. In the app, the time is rendered. This time is 00:00:00 GMT 1st Jan 1970 for all messages. It is inaccurate and should not be rendered.

### Expected behavior:

The time to not be rendered.

### Actual behavior:

The inaccurate time is rendered.

### PR DESCRIPTION
**Pull request by aKn1ghtOut**
## Proposed changes

The presence of the message_link key defines if the attachment is a quote or not for the web client. Implemented this to have the same render requirement on here.

## Issue(s)	

Closes #2901

## How to test or reproduce

1. Open General channel on Open.Rocket.Chat in web client and app.
2. In the web client, the Github messages do not have the time rendered. In the app, the time is rendered. This time is 00:00:00 GMT 1st Jan 1970 for all messages. It is inaccurate and should not be rendered.

## Screenshots
Before: 
Screenshot_20210212-200448

After:
IMG_20210212_200731

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by diegolmello — COMMENTED** [review]
I disagree on having a new component doing virtually the same thing as `Reply`.
Wouldn't it be better just to fix this rule? https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/containers/message/Reply.js#L75

**Comment by aKn1ghtOut** [comment]
I do get the concern. Wondered the same.
I thought having a separate component might be better for making changes to keep in sync with the DefaultAttachment web component in the future.
I'll, however, modify it to adjust for it in the Reply component for the time being.
I'm also looking into the web DefaultAttachment component for backwards compatibility right now. Will report if I find anything else that could be useful here.

**Comment by diegolmello** [comment]
@aKn1ghtOut Can you app description and update stories?

**Comment by aKn1ghtOut** [comment]
> @aKn1ghtOut Can you app description and update stories?

Done

**Comment by aKn1ghtOut** [comment]
@diegolmello 
Updated stories and description

**Review by kresnaputra — APPROVED** [review]

**Review by diegolmello — APPROVED** [review]
This is great! Thank you :)

**Pull request merged**
