### PR TITLE
fix: don't re-encode public key when changing e2e password

### LINKED ISSUE #4803: Changing devices will no longer send encrypted messages
A sends a message to B, and both parties set E2E. However, when A changes the device and re-enters the E2E password, the messages of A and B will no longer be encrypted messages

Today, I forgot my login password because I cleaned my mobile phone, so I used the background to change my login password, and then logged in to enter the app to enter the E2E password. All messages between me and the user 400137 are clear text and no longer encrypted. I can also log in with another device to reproduce this
Screenshot_20230112-152057_Find Me

### PR DESCRIPTION
**Pull request by paviad**
## Proposed changes

When the user changes their E2E password, their public key is sent in corrupted form to the server (sent as string instead of object)

## Issue(s)	

Closes: #4803 
Resolve: 5190

## How to test or reproduce

Use the mobile app to change E2E password by opening the side menu, selecting Settings -> Security and privacy -> E2E Encryption, entering a new password and clicking "Save Changes"

Then check using mongo that the public key of the user has been saved as a string (starts with a double quote (`"`) character) instead of an object (starting with a brace (`{`) character).

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by paviad** [comment]
@reinaldonetof should I instead have submitted this PR on the develop branch?

**Comment by paviad** [comment]
Rebased all my PRs on `develop` - yes they are ready for review.

**Comment by reinaldonetof** [comment]
Hey @paviad, thanks for this PR. Yeah, you are right, the code is "stringifying" twice and wasn't needed.

However, why is closing the https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4803?

**Comment by paviad** [comment]
> Hey @paviad, thanks for this PR. Yeah, you are right, the code is "stringifying" twice and wasn't needed.
> 
> However, why is closing the #4803?

Because of this comment from the OP

https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4803#issuecomment-1386745350

**Comment by GleidsonDaniel** [comment]
Hey @paviad you don't need to keep updating your PR, it's currently in the QA queue, going through the QA team we merge your PR.

**Review by GleidsonDaniel — APPROVED** [review]

**Pull request merged**
