### PR TITLE
[FIX] Jitsi breaking changes

### PR DESCRIPTION
**Pull request by diegolmello**
## Proposed changes

Jitsi Meet SDK 2.10.0 introduces a breaking change, which is failing on our CI.
Starting on 2.10.0, minimum SDK 23 is required on Android.
Let's stick to 2.9.0 for our app version 4.11.0.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by djorkaeffalexandre — APPROVED** [review]
LGTM

**Comment by ankar84** [comment]
> Starting on 2.10.0, minimum SDK 23 is required on Android.

So, that means that if RC RN app will use Jitsi 2.10.0, minimum Android version for RC RN app will be [Android 6](https://developer.android.com/about/versions/marshmallow/android-6.0-changes)?


> Let's stick to 2.9.0 for our app version 4.11.0.

@diegolmello do you plan to use modern Jitsi SDK in future versions?
Jitsi calls is a big part of my users Rocket Chat experience, so most up-to-date Jitsi version in RC RN app is preferred.
I hope next RC RN versions will use most recent stable Jitsi SDK.

**Comment by diegolmello** [comment]
@ankar84 
> So, that means that if RC RN app will use Jitsi 2.10.0, minimum Android version for RC RN app will be Android 6?

Yes.

> @diegolmello do you plan to use modern Jitsi SDK in future versions?

Sure. We're just holding to 2.9 now, because we're at the end of the release and we need to analyse properly the impact of removing SDK 21 and 22.
Also, 2.10 was released this week, so it's not that bad.

**Comment by arpsyapathy** [comment]
> @ankar84
> 
> > So, that means that if RC RN app will use Jitsi 2.10.0, minimum Android version for RC RN app will be Android 6?
> 
> Yes.


Hi! @diegolmello
In READNE.md i see **Supported Android versions: 5.0+**
Maybe it's time to change this to **Supported Android version now: 6.0+* * ?

**Comment by diegolmello** [comment]
@arpsyapathy 

> We're just holding to 2.9 now, because we're at the end of the release and we need to analyse properly the impact of removing SDK 21 and 22.

**Pull request merged**
