### PR TITLE
[FIX] Message actions on Image messages

### LINKED ISSUE #1193: Cannot reply with thread/quote to message with image only.
- Your Rocket.Chat Experimental app version: 1.20.0-wm.4.11189
- Your Rocket.Chat server version: 2.0.0 (open.rocket.chat)
- Device (or Simulator) you're running with: Samsung S9

Look for a message that is just an image with a comment. 

You cannot long press to reply to the message, quote, start a thread etc. The only action available is to open the image.

### PR DESCRIPTION
**Pull request by BrunoOliveiraDantas**
@RocketChat/ReactNative

Closes #1193 

image
image
image

### CODE REVIEW

**Comment by djorkaeffalexandre** [comment]
@BrunoOliveiraDantas can you add a gif?

**Comment by LucasSiqz** [comment]
> @BrunoOliveiraDantas can you add a gif?

Message-actions-image

**Comment by djorkaeffalexandre** [comment]
@BrunoOliveiraDantas @LucasSiqz it's falling on ci:
https://circleci.com/gh/RocketChat/Rocket.Chat.ReactNative/11385?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by diegolmello** [comment]
I'll try using `react-native-gesture-handler` as the priority onLongPress handler before reviewing this PR.
If that works properly, it would be better than always drilling onLongPress for every button.

**Comment by djorkaeffalexandre** [comment]
Was fixed by #2082.
Thanks.

**Pull request closed without merging**
