### PR TITLE
[i18n] Add missing italian strings

### PR DESCRIPTION
**Pull request by aenonGit**
Italian translation was missing a lot of strings, this PR adds all the missing ones and fixes some of the existing strings.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by diegolmello** [comment]
@aenonGit Can you resolve the conflicts?

**Comment by aenonGit** [comment]
@diegolmello which conflicts?

**Comment by diegolmello** [comment]
image
I wasn't able to merge develop.
Can you update your branch?

**Comment by aenonGit** [comment]
should be good now

**Review by diegolmello — APPROVED** [review]
LGTM

**Comment by diegolmello** [comment]
@aenonGit Merged. Thanks for your contribution.

**Pull request merged**
