### PR TITLE
Fix: Keep the Save Button Disabled Until the Status Value Changes.

### PR DESCRIPTION
**Pull request by anirbanpaulcom**
## Proposed changes

The Save button should only become focused when there is a change in the status.

## Issue(s)	

It's solving this issue: #5565.

### Expected behavior:
The Save button should remain unfocused until there is a change in the value of the status. Once the status value changes, the Save button should become focused.

### Actual behavior:
WhatsApp Image 2024-02-13 at 7 19 16 PM (1)

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by anirbanpaulcom** [comment]
Hey @diegolmello , @GleidsonDaniel  Could you please take a look at this PR, Thank You.

**Comment by GleidsonDaniel** [comment]
> Hey @diegolmello , @GleidsonDaniel Could you please take a look at this PR, Thank You.

Can you make it a different color when it is deactivated?
To make it clear to the user that the button is not working.

**Comment by Amitlpu-840** [comment]
Hi @GleidsonDaniel, please take a look at this, the disabled button's colour is somewhat grey and the active colour is white, please confirm if you asked for a different colour for the disabled button. I would like to contribute to completing this PR.

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/77196415/62a10dfc-b5fc-4b9d-9372-c812a96440ec

**Comment by GleidsonDaniel** [comment]
> Hi @GleidsonDaniel, please take a look at this, the disabled button's colour is somewhat grey and the active colour is white, please confirm if you asked for a different colour for the disabled button. I would like to contribute to completing this PR.
> 
>  WhatsApp.Video.2024-05-07.at.23.23.01.mp4

Yes, its correct.

**Comment by Amitlpu-840** [comment]
that's great, this PR is missing code formatting only, @anirbanpaulcom could you please merge the PR which I made to your branch with formatted code?

**Comment by anirbanpaulcom** [comment]
> Can you make it a different color when it is deactivated? To make it clear to the user that the button is not working.

@GleidsonDaniel It already has that. Are there any changes needed?

@Amitlpu-840 Thank you for your PR.

**Comment by anirbanpaulcom** [comment]
Hey @GleidsonDaniel, could you please take a look when you have some time? Thank you!

**Comment by anirbanpaulcom** [comment]
Hey @GleidsonDaniel, could you please take a look when you have some time? Thank you!

**Review by GleidsonDaniel — APPROVED** [review]

**Pull request merged**
