### PR TITLE
fix: disable full screen video on iOS jitsi calls

### PR DESCRIPTION
**Pull request by GleidsonDaniel**
## Proposed changes

https://github.com/react-native-webview/react-native-webview/issues/1035#issuecomment-956006729

## Issue(s)	

resolves: #5113

## Screenshots

before:

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/18687097/bc64562a-98e0-4c2e-b592-9e6a6be3cd40

After:

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/18687097/298d3d13-fe0b-4d6a-bc20-5a609eb77c92

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

Jira: [VC-122]

[VC-122]: https://rocketchat.atlassian.net/browse/VC-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by diegolmello — APPROVED** [review]
I'm _pretty_ sure Prettier should have removed the `={true}` part.
Are you sure you're using Prettier?

**Comment by GleidsonDaniel** [comment]
> I'm _pretty_ sure Prettier should have removed the `={true}` part. Are you sure you're using Prettier?

Yes, I'm using Prettier, but I removed it anyway.

**Comment by ankar84** [comment]
@GleidsonDaniel thank you for such fast fix!
I have a very important additional to problem and to test of that fix.
Screen Sharing of any of call participant leads to same Live\Live Broadcast layer. But screen sharing itself shows on that screen (it's not black in that case), one important problem - user don't see call manage buttons (mute\unmute, enable\disable camera, finish call). And users comply about that.

**Comment by GleidsonDaniel** [comment]
> @GleidsonDaniel thank you for such fast fix! I have a very important additional to problem and to test of that fix. Screen Sharing of any of call participant leads to same Live\Live Broadcast layer. But screen sharing itself shows on that screen (it's not black in that case), one important problem - user don't see call manage buttons (mute\unmute, enable\disable camera, finish call). And users comply about that.

Can you send a video with the example of the problem, because I did not understand the problem.
Here the buttons appear normally.

**Comment by ankar84** [comment]
> > @GleidsonDaniel thank you for such fast fix! I have a very important additional to problem and to test of that fix. Screen Sharing of any of call participant leads to same Live\Live Broadcast layer. But screen sharing itself shows on that screen (it's not black in that case), one important problem - user don't see call manage buttons (mute\unmute, enable\disable camera, finish call). And users comply about that.
> 
> Can you send a video with the example of the problem, because I did not understand the problem. Here the buttons appear normally. In addition to not understanding, I think this fix solves it, since you said it goes to full screen. But I really don't know what you're talking about.

Hey, @GleidsonDaniel 
Actually I have tested your fix and can say that it fixes Screen Sharing too.

One little problem with your fix now is that if you start a call and turn on the camera and then turn it off, it's like it's not working anymore.. but if you turn on the general view, then the camera is ok. In fact, the view switches and does not show the camera.
It described by [Chirtep](https://github.com/Chirtep) [here](https://open.rocket.chat/channel/react-native?msg=vNKo2Nyw5owCFiJFv). Android don't have such problem - if you enable camera, then disable it and then enable it again - you will see it on screen that it works. iOS now doesn't show camera, but it user switched to main (general) view - camera will be shows working.

If that little problem will be fixed now, then Android and iOS will work the same.

**Comment by ankar84** [comment]
Hey @GleidsonDaniel @diegolmello 
Any news about that fix?
As I mentioned earlier - fix works almost perfect. Black screen is fixed. But one problem with camera still remain.

**Comment by GleidsonDaniel** [comment]
> Hey @GleidsonDaniel @diegolmello Any news about that fix? As I mentioned earlier - fix works almost perfect. Black screen is fixed. But one problem with camera still remain.

Fixed

**Comment by Chirtep** [comment]
> 

Unfortunately, the problem has not been fixed. We have put together a test build based on your merge request with hash 9ad293138155724920c2ef3f292ba971fac7120d,
it also includes these comits:

https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5117/commits/5cd3648f3e42a0bce49ccf87222d8de33d62d52c

https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5117/commits/68ef60b57a161e5cf5f4654f36b77b4ef2465804

However, the problem with overlapping the camera after one activation persists. Tested on iPhone 12.

**Comment by ankar84** [comment]
Tested last commit and can that that now it is perfectly fixes black layer bug and camera works perfect all the time!
Thank you @GleidsonDaniel  and @Chirtep

**Pull request merged**
