### PR TITLE
[IMPROVEMENT] i18n Adding Arabic Translation

### PR DESCRIPTION
**Pull request by abalhamoud**
## Proposed changes
Arabic translation for Rocketchat
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

Thanks to @AlkindiX for the initial translation. **Please add him as a contributor :)**

### CODE REVIEW

**Comment by diegolmello** [comment]
@abalhamoud Before my review, I need to know about RTL: is it working properly?
I'm saying this just because this whole navigation pattern is completely different and so I can't really tell if it's correct or not.

**Comment by abalhamoud** [comment]
@diegolmello I am running into problems while trying to run the app locally. Could you share the screen instead so I can check?
Thanks

**Comment by abalhamoud** [comment]
@diegolmello I get white screen when launching the app with an Arabic device but it works when I make English the device default language and then change the app language from the settings I don't know if the issue is from the app or the device. 

Also I found few labels that didn't get translated for some reason even though I have matched all English locale keys. 
Here is one: 
https://user-images.githubusercontent.com/10301923/95614709-9b6a1380-0a6f-11eb-9f6e-ec3ab0c0aca2.png

And the sidebar is not working too when I use Arabic as the device language. (after bypassing the main screen using English language): 
https://user-images.githubusercontent.com/10301923/95614955-15020180-0a70-11eb-8ef0-a806d40b20f7.png


Other than that everything is working properly :)

**Comment by diegolmello** [comment]
@abalhamoud Thanks for testing.
We'll have to take a look on these issues before merging Arabic translation and that's going to [require some work on react-navigation](https://reactnavigation.org/docs/limitations/#limited-right-to-left-rtl-layout-support) and on other stuff.

**Comment by abalhamoud** [comment]
@diegolmello Sure. I would be happy to help anytime if needed. 

This is the error logs when launching the app and the screen becomes empty white: 
https://pastebin.com/YSv1Zjvw

screenshot:

**Comment by abalhamoud** [comment]
@diegolmello adding ` android:supportsRtl="true"` to AndroidManifest and setting `I18nManager.allowRTL(isRTL);` seems to solve the sidebar issue!

For the white screen it turns out I get it also with English language too. I don't know what's the issue there.

**Comment by diegolmello** [comment]
@abalhamoud I had a look here and it looks like it needs some work (as we expected).
I'll leave this PR open and hopefully we can get it merged for next releases.
Thanks!

**Comment by matinzd** [comment]
There is a problem changing app direction on the fly with react-native I18Manager. We have to reload the bundle again to make all layouts' directions changed.

**Review by diegolmello — APPROVED** [review]
LGTM

**Comment by diegolmello** [comment]
@abalhamoud @matinzd We [added support to RTL](#2656) recently and so this PR will work :)
I'm merging so we can test it on the Experimental app (we'll try releasing a new version on the next days), but I see some missing strings on this translation.
Can you please create a new one finishing or tweaking any incorrect ones?
Thank you.

**Comment by abalhamoud** [comment]
Thanks @diegolmello, Sure thing I will try to complete the remaining strings and open a new PR on the next couple days.

**Pull request merged**
