### PR TITLE
[I18N] Add Turkish

### PR DESCRIPTION
**Pull request by mukerremyilmaz**
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by diegolmello — COMMENTED** [review]
I really appreciate your contribution, @mukerremyilmaz.
There're 2 new keys merged earlier today: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/i18n/locales/en.js#L706
Can you add them?

**Comment by mukerremyilmaz** [comment]
Thank you @diegolmello... I have added new two lines...

**Review by diegolmello — APPROVED** [review]
LGTM

**Comment by diegolmello** [comment]
Merged!

@mukerremyilmaz during my tests, I thought you didn't have translated `theme`, so I took a look and `Tema` is the same on `pt-BR` and `tr` hahaha

**Pull request merged**
