### PR TITLE
[FIX] Missing locales in moment helper

### PR DESCRIPTION
**Pull request by zaphod534**
## Proposed changes
Add missing locales in moment helper

## Issue(s)	
Missing locales in moment helper

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by djorkaeffalexandre — CHANGES_REQUESTED** [review]

**Review by diegolmello — APPROVED** [review]

**Comment by diegolmello** [comment]
@zaphod534 Can you update your branch?

**Comment by zaphod534** [comment]
@diegolmello updated

**Comment by diegolmello** [comment]
@zaphod534 Again, I can't update your branch.
Do you know why?

image

**Comment by zaphod534** [comment]
@diegolmello now it should be working

**Comment by diegolmello** [comment]
@zaphod534 Merged. Thank you!

**Pull request merged**
