### PR TITLE
[FIX] Joining and leaving messages in teams

### LINKED ISSUE #3590: Joining and leaving messages are not displayed in teams
### Description:

When a user joins or leaves a channel , an automatic message is sent with the information "User has joined/left the channel". While the same is expected to happen when joining/leaving a team but rather it does not happen. 

A message without any content, containing only username of the user is sent in the team.

mobile-view1

Corresponding web view:

tem-webview

In fact these messages should not respond to taps(In the way messages in the channels are). But these can be edited and can even be replied to.

mobile-view2

### Environment Information

- Rocket.Chat Server Version: 
- Rocket.Chat App Version:  4.23.0
- Device Name: LG G8X
- OS Version: Android 11

### Steps to reproduce:

1. Join a team using the invite link or leave one.
2. You will be able to see the generated messages that only have the username and nothing else.

### Expected behavior:

The corresponding message like the User has joined/left the team should be displayed like the ones displayed in web and desktop app.

### Actual behavior:

These empty messages are displayed.

### PR DESCRIPTION
**Pull request by try-catch-stack**
## Proposed changes

When a user joined a team using the invite link or left the team, no messages were shown in the way they are in web and desktop app.While these were correctly shown in channels , the issue was only with teams.

## Issue(s)	

Fixes #3590 

## How to test or reproduce

Join a team using the invite like or leave any channel , an automatic message will be sent in the team that contains only username of the user and nothing else. This message is supposed to be "User has joined/left the team".
More on it in the issue tagged above.

## Screenshots

Earlier:
mobile-view1

Now:
mobile-view

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [X] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by try-catch-stack** [comment]
@diegolmello @GleidsonDaniel Can you please review the changes?

**Comment by GleidsonDaniel** [comment]
> @diegolmello @GleidsonDaniel Can you please review the changes?

I'll take a look and check.

@try-catch-stack Can you resolve conflicts?

**Comment by try-catch-stack** [comment]
Done

**Comment by try-catch-stack** [comment]
@GleidsonDaniel Any updates?

**Review by GleidsonDaniel — APPROVED** [review]
LGTM
@diegolmello Can you just double check?
I tested it here on my device and it worked as expected.

**Comment by GleidsonDaniel** [comment]
> @GleidsonDaniel Any updates?

Can you update the branch?

**Comment by diegolmello** [comment]
I'll take a look in a bit

**Review by diegolmello — APPROVED** [review]

**Comment by diegolmello** [comment]
Merged. Thanks a lot, @try-catch-stack! 👏🏼 👏🏼 👏🏼

**Comment by try-catch-stack** [comment]
It is my pleasure to contribute to such a great product used by people all around the globe :)
Looking forward to add even more value to the community .

**Pull request merged**
