### PR TITLE
build: Update minSdkVersion = 23 to resolve Manifest merger failed

### PR DESCRIPTION
**Pull request by ceefour**
## Proposed changes

Fix for: Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [org.jitsi.react:jitsi-meet-sdk:2.10.0]

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by diegolmello** [comment]
We always update `single-server` branch after a new release.
On version 4.11, we opted for keeping Android SDK 21 and announce properly when we remove them.

**Comment by ceefour** [comment]
@diegolmello but currently this project cannot be built due to jitsi-meet-sdk requiring minSdk 23?

Can you suggest the proper solution instead if still using minSdk 21?

**Comment by diegolmello** [comment]
@ceefour We're going to update the branch in next week, but if you can't wait check https://github.com/RocketChat/Rocket.Chat.ReactNative/commit/709c7aaaea5815fcd60579c6d9390be0baf5a229

**Comment by ceefour** [comment]
Thank you @diegolmello. That is very helpful! 🙏

I assume the update next week would be for 4.10 right? Since currently single-server is still on 4.9.

**Comment by diegolmello** [comment]
@ceefour Nope, single-server is 4.10 already.
I just didn't update [Android version](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/single-server/android/gradle.properties#L29). It's updated on [iOS](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/single-server/ios/RocketChatRN/Info.plist#L22).

**Pull request closed without merging**
