### PR TITLE
fix: resolve ts-ignore issues for legal in settings view

### PR DESCRIPTION
**Pull request by Rohit3523**
## Proposed changes
This PR removes the use of `@ts-ignore` for the Legal button in the SettingsView component by properly addressing the underlying TypeScript issues. Types have been updated or adjusted to ensure compatibility, and the code has been refactored to maintain type safety and functionality. All changes have been tested to confirm the button's functionality and adherence to TypeScript standards

## Issue(s)	
N/A

## How to test or reproduce
N/A

## Types of changes
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by diegolmello** [comment]
Lint is failing

**Comment by OtavioStasiak** [comment]
Hi Rohit, thank you for your contribution! 
We have other screens where we can use `useNavigation` instead of passing navigation as props. Could you please adjust all applicable screens to use `useNavigation`? For example: `SendEmailConfirmationView`.

**Comment by Rohit3523** [comment]
@OtavioStasiak Sure, I can do it, but can I open another PR for that? Since you already have a feature branch and this PR is going to merge into it, I am thinking of creating a separate PR for this to keep everything organized and focused.

**Comment by Rohit3523** [comment]
@diegolmello I have fixed the lint errors

Screenshot 2024-12-16 at 11 31 32 PM

**Pull request closed without merging**
