### PR TITLE
fix RTL on RoomViewActions

### LINKED ISSUE #842: RTL problem with roomActionsView
- RTL problem on RoomActionsView 
rtlproblem

### PR DESCRIPTION
**Pull request by kareemhamdy100**
@RocketChat/ReactNative

Closes #842

rtlSolved

### CODE REVIEW

**Comment by kareemhamdy100** [comment]
> What about the rest of the app?
> Doest it work for RTL?

I just noticed that the roomslist view needed to be modified to support rtl 
Screenshot_٢٠١٩-٠٤-٢٤-٢١-٤٩-١٦-٥١٠_chat rocket reactnative

**Comment by diegolmello** [comment]
@kareemhamdy100 we don't support RTL yet.
If you develop this, you'll probably have to do it in the entire app.
Will you add arabic translation as well? :)

**Comment by kareemhamdy100** [comment]
> @kareemhamdy100 we don't support RTL yet.
> If you develop this, you'll probably have to do it in the entire app.
> Will you add arabic translation as well? :)

yes I could add arabic translation  
I will check all the entire app as well

**Comment by diegolmello** [comment]
> > @kareemhamdy100 we don't support RTL yet.
> > If you develop this, you'll probably have to do it in the entire app.
> > Will you add arabic translation as well? :)
> 
> yes I could add arabic translation
> I will check all the entire app as well

Awesome! Thanks 👍

**Pull request closed without merging**
