### PR TITLE
[FIX] Connecting stream listener not being cleared

### PR DESCRIPTION
**Pull request by nmagedman**
## Proposed changes

PR #2894 added a new event listener, but did not store it properly (immediately overwrites it with another listener -- looks like a copypasta error).  Further, it did it stop the new listener along with all the other listeners,

See discussion @ https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2894#discussion_r598995840

## Issue(s)	

We have been experiencing problems with deeplinking since our recent RC server upgrade (v3.12.1) that may or may not be related to this bug.  While reviewing recent commits, I noticed this glitch in the code.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by diegolmello** [comment]
Thank you, @nmagedman.
Can you open an issue regarding that deep linking glitch?

**Comment by nmagedman** [comment]
> Can you open an issue regarding that deep linking glitch?

Someone beat me to it.  #2987 is exactly the issue we are seeing.

**Comment by diegolmello** [comment]
@nmagedman Excellent! We're fixing that right now.
We'll also going to write E2E tests for the whole deep linking process, so we can prevent more regressions.

**Comment by nmagedman** [comment]
@diegolmello I'm not clear how to move forward with this PR.

**Comment by diegolmello** [comment]
@nmagedman it's going to be merged soon

**Comment by HiveMindNet** [comment]
@diegolmello @nmagedman - any progress with this deeplinking issue please?

@nmagedman - did you put in a temp fix for this in the meantime? Would you mind please sharing if so? We're stuck on this for quite a while! :)

Thanks both

**Comment by diegolmello** [comment]
We've been holding this to be merged for 4.17.0.
We just released 4.16.2, so we can merge it on 4.17 later this week.
The release is going to happen in a few weeks.

**Review by diegolmello — APPROVED** [review]

**Comment by diegolmello** [comment]
@HiveMindNet yes :)

**Pull request merged**
