### PR TITLE
fix: made the description of channels in directory same as lastmessage

### LINKED ISSUE #5387: The descriptions in directory channels render links instead of presenting plain text.
### Description:

In the directory, the channels' description shows the link rather than showing text.
WhatsApp Image 2023-12-10 at 12 22 14

The text renders the topic from the room info of the channel.
WhatsApp Image 2023-12-10 at 12 22 30

I think it would be better to render text there (for example we can show Text1 | Text2 | Text3 in the description rather than `[Text1](Link1) | [Text2](Link2) | [Text3](Link3)` in the directory

### Environment Information:

- Rocket.Chat Server Version: 6.5
- Rocket.Chat App Version: 4.43
- Device Name: Samsung Galaxy M13 5G
- OS Version: Ubuntu 22.04
- Android Version: 13

### Steps to reproduce:

1. Go to directory
2. Check the description of the channel

### Expected behavior:

The description should display simple text.

### Actual behavior:

Shows link `(text1)[link1]`

### PR DESCRIPTION
**Pull request by brf153**
## Proposed changes

Before:
WhatsApp Image 2023-12-10 at 12 22 14 (1)

After:
WhatsApp Image 2023-12-13 at 18 44 10

## Issue(s)	

closes #5387 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by brf153** [comment]
@diegolmello I have fixed the issue #5387

**Comment by diegolmello** [comment]
@brf153 Awesome. I'm going to try a review later today, but I'm pretty sure it's about it. Thanks!

**Review by diegolmello — APPROVED** [review]
lgtm

**Comment by diegolmello** [comment]
Merged. Thanks, @brf153! 🙏🏼

**Pull request merged**
