### PR TITLE
[FIX] Make attachment validation compatible with web client

### LINKED ISSUE #2926: [BUG] App renders attachments differently from Web Client
### Description:

While using the message object example from the [Docs page](https://docs.rocket.chat/api/rest-api/methods/chat/postmessage) :
`{
  "alias": "Gruggy",
  "avatar": "http://res.guggy.com/logo_128.png",
  "channel": "#general",
  "emoji": ":smirk:",
  "roomId": "Xnb2kLD2Pnhdwe3RH",
  "text": "Sample message",
  "attachments": [
    {
      "audio_url": "http://www.w3schools.com/tags/horse.mp3",
      "author_icon": "https://avatars.githubusercontent.com/u/850391?v=3",
      "author_link": "https://rocket.chat/",
      "author_name": "Bradley Hilton",
      "collapsed": false,
      "color": "#ff0000",
      "fields": [
        {
          "short": true,
          "title": "Test",
          "value": "Testing out something or other"
        },
        {
          "short": true,
          "title": "Another Test",
          "value": "[Link](https://google.com/) something and this and that."
        }
      ],
      "image_url": "http://res.guggy.com/logo_128.png",
      "message_link": "https://google.com",
      "text": "Yay for gruggy!",
      "thumb_url": "http://res.guggy.com/logo_128.png",
      "title": "Attachment Example",
      "title_link": "https://youtube.com",
      "title_link_download": true,
      "ts": "2016-12-09T16:53:06.761Z",
      "video_url": "http://www.w3schools.com/tags/movie.mp4"
    }
  ]
}`
, the message shows differently on the web client and the app.

On Web client: 
Screenshot from 2021-02-20 15-18-49

On App: 
Screenshot_20210220-152344_ DEBUG _Rocket Chat_Experimental_2

The client checks for the 'type' of all the file attachments while the ReactNative app currently does not. This makes differences in presentations like this possible.

### Environment Information:

- Rocket.Chat Server Version: 3.11
- Rocket.Chat App Version: 4.14.1
- Device Name: Nexus 6P
- OS Version: Android 11

### Steps to reproduce:

Use the above messageObject and look at the resulting message on both the clients.

### Expected behavior:

Both the clients to follow the same scheme.

### Actual behavior:

The attachment is rendered as an ImageAttachment instead. The image does not load because the url in the example messageobject isn't valid anymore.

### Additional context:

Fix PR ready

### PR DESCRIPTION
**Pull request by aKn1ghtOut**
## Proposed changes

Added checking of attachment.type to make it similar to the web client, and make rendering more consistent. This uses the Reply component is the file type checking does not pass.
Look at: https://github.com/RocketChat/Rocket.Chat/blob/fea5a7a8a1afce45c81d5776dd264ccf02985fa4/client/components/Message/Attachments/Files/index.tsx#L29

## Issue(s)	

Closes #2926 

## How to test or reproduce

Look at issue #2926 

### On Web client: 
Screenshot from 2021-02-20 15-18-49

### Before:
Screenshot_20210220-152344_ DEBUG _Rocket Chat_Experimental_2

### After:
Screenshot_20210220-152344_ DEBUG _Rocket Chat_Experimental_3

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

The fields do not show in the web client for quote attachments, even if they're still in the message. In my opinion, that should be corrected on the web client as the fields key existing in the message warrants the render. There isn't any additional type/integrity checking that suggests it should be hidden. They do not render just because it's not included in the QuoteAttachment component yet.

### CODE REVIEW

**Comment by diegolmello** [comment]
@aKn1ghtOut Amazing.
You got the drill: can you add stories? :)
Thanks! 👊

**Comment by aKn1ghtOut** [comment]
> @aKn1ghtOut Amazing.
> You got the drill: can you add stories? :)
> Thanks! 👊 

On it for all PRs :)

**Comment by aKn1ghtOut** [comment]
Done adding stories to all recent PRs @diegolmello

**Review by kresnaputra — APPROVED** [review]

**Review by diegolmello — APPROVED** [review]
LGTM

**Pull request merged**
