### PR TITLE
[BUG] App isn't showing message for PDF/file uploads

### PR DESCRIPTION
**Pull request by saket-m0**
## Proposed changes

The app now shows the message entered with the pdf or other files on sending.

In app/containers/message/Reply.js added an if statement to check if file description exists and if yes then add a markdown with value msg equal to the description.

Also tested using 'yarn test -u' to add/update the tests.

## Issue(s)	

Fixing the issue #2531 
## Screenshots
The text entered while sending the file is visible in the development version now (Refer to the latest attachment sent).
Screenshot_20201010-000013_ DEBUG  RocketChat Experimental

The same text is not visible in the production version (Refer to the latest attachment sent).
Screenshot_20201009-234131_RocketChat

## Types of changes

- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ x ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ x ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ x ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ x ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

I am new to Opensource. Please let me know if I have done something wrong so that I can Fix It. Thank You!

### CODE REVIEW

**Review by diegolmello — CHANGES_REQUESTED** [review]
I couldn't find the if statement mentioned on the description and markdown is rendering inside the touchable.

image

**Comment by saket-m0** [comment]
I removed the if statement as one of the maintainers told me there is no need for the if statement.

I have fixed my mistake in the return statement and moved markdown outside the touchable.

**Review by diegolmello — APPROVED** [review]
LGTM

**Comment by diegolmello** [comment]
@saket-m0  I've tweaked it a bit in order to merge. You can check my changes. Thanks.

**Comment by saket-m0** [comment]
Thanks a lot! :)

**Pull request merged**
