### PR TITLE
[FIX] Bugsnag key not found

### PR DESCRIPTION
**Pull request by emikolajczak**
From version 4.19.0 single-server is not possible to build iOS version.

## Proposed changes
Fix for "Bugsnag key not found` error during build "single-server" version

## How to test or reproduce
Build "single-server" version

## Types of changes
Remove line 44 `dsym_path: "./ios/Rocket.Chat.app.dSYM.zip",`

- [x ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by emikolajczak** [comment]
Hi, any chance to merge it into `single-server`?

**Comment by diegolmello** [comment]
> Hi, any chance to merge it into `single-server`?

@emikolajczak It's working properly on our CI. What are you aiming to fix here?
image

**Comment by emikolajczak** [comment]
I cant build `single-server` without this change. May it cause I not using Bugsnag?

**Comment by diegolmello** [comment]
@emikolajczak Probably, yes. You should remove Bugsnag completely before building (or keep only removing that line if it's ok to you).
I'm closing.
Thanks!

**Pull request closed without merging**
