### PR TITLE
[IMPROVE]Added text color to markdown links 

### LINKED ISSUE #2841: Markdown links coloured same as normal text.
### Description:
Markdown links in some places have same color as of normal text, making it impossible for user to know if some text contains hyperlinks or not.

### Environment Information:

- Rocket.Chat Server Version: 3.11.0-develop
- Rocket.Chat App Version: 4.14.0
- Device Name: Pixel Emulator
- OS Version: Android 10

### Steps to reproduce:

1.  Goto room info
2.  Set announcements and Topic as [sampleText](some hyperLink)

### Expected behavior:

Markdown links should be rendered with different color
image

### Actual behavior:
Markdown links and normal text have same color

image

### Additional context:
On website it looks like this -
image

### PR DESCRIPTION
**Pull request by yash-rajpal**
## Proposed changes

Added tint color to markdown links. This can help people to easily distinguish normal text and links
## Issue(s)	

fixes #2841 
## How to test or reproduce

Check issue
## Screenshots
image

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

Added check in renderText of Markdowns, if context contains link, i.e this piece of text is a hyperlink, so added tint color for this.

### CODE REVIEW

**Comment by yash-rajpal** [comment]
@diegolmello Please review, :)

**Review by diegolmello — CHANGES_REQUESTED** [review]
This is not the best place to do that.
You want to be changing it here https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/containers/markdown/Link.js#L33

**Comment by yash-rajpal** [comment]
@diegolmello 

Yes Sir, you are right, most of links are rendered using Link component which you mentioned, but the component you mentioned already contains the textColor - `actionTintColor`.

But some links are not rendered through Link component you mentioned, instead they are rendered by `renderText` component, due to which they are not coloured. 
In this case the property `context` contains value `link` if the text is supposed to be a link. That's why here I am checking if `context` contains `link` then give it `tintcolor`.

I have checked it thoroughly and if you want I can attach ScreenShots of console logs within renderText and it contains `context` as `link`.

Thanks. :)

**Comment by diegolmello** [comment]
> @diegolmello
> 
> Yes Sir, you are right, most of links are rendered using Link component which you mentioned, but the component you mentioned already contains the textColor - `actionTintColor`.
> 
> But some links are not rendered through Link component you mentioned, instead they are rendered by `renderText` component, due to which they are not coloured.
> In this case the property `context` contains value `link` if the text is supposed to be a link. That's why here I am checking if `context` contains `link` then give it `tintcolor`.
> 
> I have checked it thoroughly and if you want I can attach ScreenShots of console logs within renderText and it contains `context` as `link`.
> 
> Thanks. :)

If that's the case, it's an issue on the markdown renderer and it should be fixed there.
Your fix tries to workaround the markdown by adding a specific rule.
What kind of link is not rendered correctly?
I don't know what you're fixing really.

**Comment by yash-rajpal** [comment]
Yes sir, I agree, its a workaround for links rendered by `renderText`.

But I don't know why some links are not being rendered by `Link` component.

I tried by changing a room's announcement to -

This is some text and link -  [Google](https://www.google.co.in/) and some more [Google](https://www.google.co.in/)

I changed room announcement or room topic to above text and links were not being rendered by the `Link` component.

Can you suggest how should I fix this? I see only this workaround.

**Comment by diegolmello** [comment]
Here's where commonmark parses URLs https://github.com/RocketChat/commonmark.js/blob/master/lib/inlines.js#L842
Here's the React part https://github.com/RocketChat/commonmark-react-renderer/blob/master/src/commonmark-react-renderer.js#L245

**Comment by yash-rajpal** [comment]
@diegolmello Sure, I will try to solve this issue from the lib part itself. Thanks for letting me know.

**Pull request closed without merging**
