### PR TITLE
[FIX] Media share type

### LINKED ISSUE #1084: [Bug] Share Media e.g. Images to File Upload -> Error
I tried to share Images from **WhatsApp** to RocketChat Client but a Error is appear ... 
WhatsApp Image 2019-07-30 at 03 13 23
WhatsApp Image 2019-07-30 at 03 13 23-2

After this the Error will not send the Content... :( 

I use last **Dev (Nightly)**, RocketChat Server is Dev Instance too....

### PR DESCRIPTION
**Pull request by djorkaeffalexandre**
@RocketChat/ReactNative

Closes #1084

### CODE REVIEW

**Comment by DoM1niC** [comment]
Ty :) all works here now but Audio Messages sharing will not working but it's not needed 4 me but a note 4 the Devs!

**Comment by djorkaeffalexandre** [comment]
@DoM1niC Hello, audio message sharing from which app is crashing?

**Comment by djorkaeffalexandre** [comment]
Here it works

**Comment by diegolmello** [comment]
@djorkaeffalexandre It doesn't seem to work on Android though.

@DoM1niC Can you open an issue? Thanks!

**Pull request merged**
