### PR TITLE
[FIX] Share extension not working correctly on Official app

### LINKED ISSUE #2819: In iPad mini 5th generation can't share photo from the Files or Photos app to chat
### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version:
- Device Name:  iPad mini 5th generation 
- OS Version: 14.2

### Steps to reproduce:

1.  Go to 'Photos' 
2. Click on 'share icon'
3. Select Rocket Chat 

### Expected behavior:

 What we expect to happen
It souls share the photo with the chat in Rocket chat. and should open chat list in dialog.
### Actual behavior:

What actually happens with SCREENSHOT

http://prnt.sc/xcj627

### LINKED ISSUE #2877: iOS App Version 4.14.1 - Dialog for Sharing Files is blank
### Description:

Eventought this issue was solved for some, it still keeps happening to me:
When using the option for sharing files on iOS with the updated version (4.14.1) of the Rocket.Chat App, a blank dialog appears (refer to the video below). 

### Environment Information:

- Rocket.Chat Server Version: 3.9.7
- Rocket.Chat App Version: 4.14.1.22787
- Device Name: iPhone 12 256GB
- OS Version: iOS 14.4

### Steps to reproduce:

1. Open any App on iOS which lets you use the share option (I tested it with Photos and Safari)
2. Click on the iOS share icon 
3. Click on the Rocket.Chat App

### Expected behavior:

One would expect Rocket.Chat to open to share the content. 

### Actual behavior:

Unfortunately only a blank dialog appears (refer to video below). 
Actual Behaviour:

https://user-images.githubusercontent.com/77775128/107050570-accbee00-67cb-11eb-92e5-4a3462304c17.mp4

### Additional context:

I performed a restart of my iPhone after updating the App to Version 4.14.1. This did not solve the issue. 
Refer to the initial issue #2760 where the problems seemed to get solved for some users.
Thank you in advance!

### PR DESCRIPTION
**Pull request by diegolmello**
## Proposed changes

On #2701 we create new entries on Info.plist, but they weren't added to all targets.

## Issue(s)	

Closes #2877
Closes #2819

## How to test or reproduce

- Install Rocket.Chat official (without having Experimental on the same device)
- Try to share anything

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by User6554** [comment]
Hi @diegolmello, 
I can happily confirm now that the issue "Share extension not working on iOS" **does work for me on my iPhone 12 with the new TestFlight Version 4.15.0.23394!**
It does no work with the current AppStore version 4.14.1! but with the TestFlight Beta 4.15.0.23394!
Thanks a lot!

**Comment by diegolmello** [comment]
Great, @User6554.
Thanks for your feedback :)

**Comment by mgarmash** [comment]
Still does not work on my iOS 14.4.2, iPhone XS with 4.15.0.23394 from AppStore and from TestFight

https://user-images.githubusercontent.com/453401/113487401-5b8d6180-94d1-11eb-8a59-d580e66cc4bf.MP4

**Comment by serge-petrov** [comment]
I have the same issue.
Two identical servers Ubuntu 20.04:
Version
3.14.4
Apps Engine Version
1.25.0
Node Version
v12.22.1
Database Migration
222
MongoDB
3.6.14 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (ba6337c2b)
Branch: HEAD

First one works fine but the second one causes blank screen while sharing attachment from another app. I use the same iPhone SE2 and Rocket 4.16.2.23928 for both cases.

**Pull request merged**
