### PR TITLE
fix: add channel name when the text is bold

### LINKED ISSUE #5305: Channel name removed from bold text
### Description:

When a channel name used inside bold text, it will not be shown.

### Environment Information:

- Rocket.Chat Server Version: 6.4.4
- Rocket.Chat App Version: 4.42.0.50842
- Device Name: ELE-L29 (Huawei P30)
- OS Version: EMUI 12.0.0 (Android 11)

### Steps to reproduce:

1. Write the message `* #channel *`.

### Expected behavior:

The channel name is shown in the same way as in the browser:

image

### Actual behavior:

The channel name is not shown:

image

However, it is shown in the channel list:

image

And also when quoting the message:

image

(in the quote, the text is not formatted in bold face, but instead as an enumeration)

### Additional context:

This also applies for italics and strikethrough. The behaviour does not depend on whether the channel actually exists.

### PR DESCRIPTION
**Pull request by brf153**
## Proposed changes
I have fixed the bug related to the markup issue in the MENTION_CHANNEL type.

## Issue(s)	
Resolve #5305

## How to test or reproduce
Just text \*#support\* in the message box.

## Screenshots
WhatsApp Image 2023-11-05 at 17 18 34

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added the necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by brf153** [comment]
I need to make changes in the definitions.d.ts file for this change to work.

**Comment by paulchen** [comment]
@brf153 Thanks for taking care of my issue!

Would it be possible to fix this also for italics and strikethrough?

**Comment by brf153** [comment]
@paulchen oki I will look into that as well

**Comment by brf153** [comment]
@paulchen I have added the changes for strike and italic.

**Comment by GleidsonDaniel** [comment]
The lint is breaking, adding your other PR to fuselage solves the problem.
I have already contacted the engineering team to review your PR.

As soon as it has merged, we will update this one and I will review it.

**Comment by brf153** [comment]
@GleidsonDaniel thank you sir

**Comment by brf153** [comment]
@GleidsonDaniel I think we can merge this pr as well. The changes have been added to the fuselage repo. Now, the lint would not break.

**Comment by GleidsonDaniel** [comment]
I'll take a look and if it runs correctly I'll merge.

**Comment by brf153** [comment]
@GleidsonDaniel why is the lint still failing? It is working properly in my system. Even `yarn lint` does not give any error.

**Comment by GleidsonDaniel** [comment]
Yes, I noticed, last week I was solving some internal tasks here at the company.
This week I will look at your PR and others that are open, then I will send an update here.

**Review by GleidsonDaniel — APPROVED** [review]
Now it works, thanks for the PR @brf153

**Pull request merged**
