### PR TITLE
[NEW] Add sorting functionality in directory page and some improvements

### PR DESCRIPTION
**Pull request by try-catch-stack**
## Proposed changes

* Added a header in Directory page which allows the user to sort channels/teams/users by factors like member count , name etc.
* Also , previously , the dropdown menu did not close automatically on selecting any option which was not a good experience.
* The PR also includes some visual updates like adding a Featured chip in front of featured channels.

## Screenshots

https://user-images.githubusercontent.com/77742477/151169911-b15fc43f-b352-445c-8c30-a6ff6cf723c6.mp4

Light theme:
directory-light-theme

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [X] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ankar84** [comment]
Looks very useful!

**Comment by GleidsonDaniel** [comment]
As I said in the other PR, visual changes we have to confirm with our UX team, as soon as I have a feedback I'll let you know. @try-catch-stack

**Comment by try-catch-stack** [comment]
Sure @GleidsonDaniel 
Will be waiting for the feedback!

**Comment by diegolmello** [comment]
It might take a while to get to you on this one.
That kind of sorting is not the usual pattern on mobile.
It's usually done with a sorting dropdown instead.
But again, it's something the UX team should take a look first.

**Comment by try-catch-stack** [comment]
Sure, no problem (:

**Pull request closed without merging**
