### PR TITLE
[FIX] Order of quoted message done according to desktop version

### PR DESCRIPTION
**Pull request by Misterr-H**
…op version

## Proposed changes

In app/containers/message/Reply.tsx, Changed the order of <Attachments/> component

## Issue(s)	

#4646 

## How to test or reproduce

Check any chat screen with quoted messages.

## Screenshots
Screenshot 2022-12-10 at 11 28 46 PM

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] I have added necessary documentation (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by diegolmello — CHANGES_REQUESTED** [review]
Thanks for your contribution.
Can you fix lint?

**Comment by Misterr-H** [comment]
@diegolmello No sir, my apologies but I don't have idea what's causing liniting issue

**Comment by diegolmello** [comment]
Did you try `yarn test-update`?

**Comment by Misterr-H** [comment]
no

**Comment by Misterr-H** [comment]
hi @diegolmello 
I had run `yarn test-update`
Here's the output in terminal
Screenshot 2023-01-29 at 11 58 45 PM

**Comment by Misterr-H** [comment]
@diegolmello 
Please help me fixing this lint issue

**Pull request merged**
