### PR TITLE
[NEW] Add an option to change message time format

### LINKED ISSUE #3679: Add 24 hour time format
### Description:

A setting for 24 hour time format exists on the server, but not on the client apps.

1. Expose the option in the profile settings
2. Sync the setting between mobile and desktop apps

### Environment Information:

- Rocket.Chat Server Version: 4.4
- Rocket.Chat App Version: 4.24.0.28002
- Device Name: Android
- OS Version: 12

### Steps to reproduce:

1. Desktop app: Update time format in profile settings
2. Switch to mobile app, view that messages are still in 12 hour format
3. View that there is no option to switch time format in the app

### Expected behavior:

Time is shown in 24 hour format

### Actual behavior:

Time is shown in 12 hour format

### Additional context:

Tried logging out then back in to the app and that didn't work

### PR DESCRIPTION
**Pull request by try-catch-stack**
## Proposed changes

* Add an option in the preferences settings to change time format of messages.
* The setting is in sync with the server and is same across web and mobile app.

## Issue(s)	

Fixes #3679 
## Screenshots

https://user-images.githubusercontent.com/77742477/152505828-a16378e7-cd01-4283-94cf-97dd64dd2411.mp4

https://user-images.githubusercontent.com/77742477/152506942-4eb772db-11f7-406a-b7f7-20546348b0b3.mp4

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [X] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by try-catch-stack** [comment]
Thanks for the help @diegolmello :-) 
Please review!
Also can you please guide me with generating the tests (If needed) for the visual updates .

**Review by diegolmello — COMMENTED** [review]
Pretty cool!
Can you post how this is displayed on the web and links to their code?
Should we take this opportunity and do the same for the rooms list?
Thanks!

**Comment by try-catch-stack** [comment]
Yes sure!
* So [this](https://github.com/RocketChat/Rocket.Chat/blob/develop/client/views/account/preferences/PreferencesMessagesSection.js) is where the code for Preferences for Messages is. Changing the preference , calls the [api](https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/users-endpoints/set-preferences) and the corresponding Preference is also updated in the settings which can then be fetched using [getUserPreference](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/utils/lib/getUserPreference.js) function. 
* We have a helper function [formatTime](https://github.com/RocketChat/Rocket.Chat/blob/develop/client/lib/utils/formatTime.ts) which is used to format time in the 12/24 hour format while rendering messages . 
* Time from the messages is passed to the above function [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/ui-message/client/message.js#L219) .

**Comment by try-catch-stack** [comment]
Closing in favor of https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4266

**Pull request closed without merging**
