### PR TITLE
[FIX] Messages showing URL preview on Room Actions

### LINKED ISSUE #4061: [Bug] No URL preview in results when we search for messages
### Description:
When we search for messages and the result message contains a URL, there appears a transparent bar instead of a URL preview.

### Environment Information:

- Rocket.Chat Server Version: Latest
- Rocket.Chat App Version: Latest
- Device Name: iPhone 12
- OS Version: iOS

### Steps to reproduce:

1. Go to any room and then go for message search.
2. Search for a message that has URL in it.

### Expected behavior:
Either there should be a preview of the URL or we remove the transparent bar which is a placeholder for the preview.

### Actual behavior:
A transparent bar appears in place of URL preview.

### Additional context:
Screenshot 2022-04-15 at 1 36 53 AM

### LINKED ISSUE #4064: [Bug] No URL preview when we see Starred, Pinned or Mentioned messages
### Description:
When we view pinned, starred, or mentioned messages in their respective views and there is a message containing a URL, then similar to #4061 we see a transparent bar instead of a URL preview.

### Environment Information:

- Rocket.Chat Server Version: Latest
- Rocket.Chat App Version: Latest
- Device Name: iPhone 12
- OS Version: iOS

### Steps to reproduce:

1. Go to a chat and pin and star a message containing a URL.
2. Mention yourself and add a URL to that message.
3. Go to the pin, starred, or mentions messages view and check for the message containing URL.

### Expected behavior:
The message should show the preview of the URL.

### Actual behavior:
What we actually see is a transparent bar.

### Additional context:
Screenshot 2022-04-17 at 8 41 24 PM
Screenshot 2022-04-17 at 8 41 19 PM
Screenshot 2022-04-17 at 8 41 13 PM

### PR DESCRIPTION
**Pull request by samay-kothari**
## Proposed changes

When we look for pinned, mentions and starred messages in their respective views, and the message contains URL, the the URL preview gets rendered. Also when we search for messages that have URL in them, we can see URL preview there also.
## Issue(s)	

Closes #4064 
Closes #4061
## How to test or reproduce

1. Go to a chat and pin and star a message containing a URL.
2. Mention yourself and add a URL to that message.
3. Go to Room Actions >  (Either Pinned / Starred / Mentions screen) and check for the message containing the URL.
4. Search for that starred message in the chat.
Now after the changes made the URL preview can be seen for starred, pinned and mentions messages view.
### Before
Screenshot 2022-04-17 at 8 41 13 PM
Screenshot 2022-04-17 at 8 41 19 PM
Screenshot 2022-04-17 at 8 41 24 PM
163467473-0f4911ea-c0e3-44bd-a036-fbeea62bace7

### After
Screenshot 2022-04-17 at 11 14 58 PM
Screenshot 2022-04-17 at 11 14 49 PM
Screenshot 2022-04-17 at 11 14 44 PM
163540006-e81f89c8-f1f9-4758-ba7a-2db2fd3e2914

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by samay-kothari** [comment]
Hi @gerzonc 
Can you review this PR as well, this solves the issue of URL not rendering when in mentions, starred and pinned messages view.

**Review by gerzonc — APPROVED** [review]
LGTM

**Comment by samay-kothari** [comment]
@diegolmello can you merge this?

**Comment by gerzonc** [comment]
> @diegolmello can you merge this?

We need to test it first before merging; I can do it myself, but still need QA approval in order to do so

**Comment by samay-kothari** [comment]
> We need to test it first before merging; I can do it myself, but still need QA approval in order to do so
Hi @gerzonc 
Who will be giving the approval for that?

**Comment by gerzonc** [comment]
> > We need to test it first before merging; I can do it myself, but still need QA approval in order to do so
> 
> Hi @gerzonc Who will be giving the approval for that?

QA team. They need to test it and once approved, it can be merged.  We need to be patient.

**Comment by samay-kothari** [comment]
> QA team. They need to test it and once approved, it can be merged. We need to be patient.

Ohh, yeah yeah no hurry, I was not aware of the process.

**Comment by gerzonc** [comment]
Can you solve conflicts?

**Comment by samay-kothari** [comment]
@gerzonc 
Done
Resolved the conflicts

**Pull request merged**
