### PR TITLE
[FIX] Gitlab url hardcoded problem 

### LINKED ISSUE #251: Gitlab url hardcoded
- Your Rocket.Chat.Android app version: latest
- Your Rocket.Chat server version: 0.62.2

Gitlab OAuth is limited only to gitlab.com, becouse url is hardcoded (https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/views/LoginView.js#L109)

Because of my limited knowledge in react-native (and JS), I wasn't able to fixed this issue.

On server add action, server returns all settings. Among these settings, there is one like this:
```
{
"_id":"API_Gitlab_URL",
"value":"https://gitlab.example.com/",
...
}
```

Could someone please look into this and implements different urls for gitlab oauth?

Thanks.

### PR DESCRIPTION
**Pull request by lolimay**
@RocketChat/ReactNative

Closes #251

### CODE REVIEW

**Comment by diegolmello** [comment]
@lolimay Hi. Is this PR a work in progress? It doesn't seem to fix #251

**Comment by lolimay** [comment]
> @lolimay Hi. Is this PR a work in progress? It doesn't seem to fix #251

Yes, I want to get `API_Gitlab_URL` through `http://localhost:3000/api/v1/settings.public` first. Is any good idea to get that setting option?

**Comment by diegolmello** [comment]
> > @lolimay Hi. Is this PR a work in progress? It doesn't seem to fix #251
> 
> Yes, I want to get `API_Gitlab_URL` through `api/v1/settings.public` first. Is any good idea to get that setting option?

Yes.
We fetch settings here: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/methods/getSettings.js#L23
And these are the settings we look for: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/constants/settings.js

You can just add `API_Gitlab_URL` to the list and it'll be in the settings reducer already.

**Comment by lolimay** [comment]
> > > @lolimay Hi. Is this PR a work in progress? It doesn't seem to fix #251
> > 
> > 
> > Yes, I want to get `API_Gitlab_URL` through `api/v1/settings.public` first. Is any good idea to get that setting option?
> 
> Yes.
> We fetch settings here: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/methods/getSettings.js#L23
> And these are the settings we look for: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/constants/settings.js
> 
> You can just add `API_Gitlab_URL` to the list and it'll be in the settings reducer already.

Thank you!

**Comment by lolimay** [comment]
Done!

**Comment by IlarionHalushka** [comment]
ios build fails 🤔

**Comment by lolimay** [comment]
> ios build fails

In the commit [aeeadd2](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/921/commits/aeeadd25bb3d568e02e877f38312231111f5512a), I only correct the constant variable API_Gitlab_URL 's type in `app/constants/settings.js`.

**Comment by lolimay** [comment]
It's really odd that [a819a78](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/921/commits/a819a78494e8c7f353af162d952e56e593d669ae) is passed but [aeeadd2](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/921/commits/aeeadd25bb3d568e02e877f38312231111f5512a) not 😲

**Comment by IlarionHalushka** [comment]
how did you test it that it actually works?

**Comment by lolimay** [comment]
> how did you test it that it actually works?

Yes, it works as expected.

deepin-screen-recorder_Select area_20190528092411

**Comment by diegolmello** [comment]
> > how did you test it that it actually works?
> 
> Yes, it works as expected.
> 
> deepin-screen-recorder_Select area_20190528092411

Is it working on https://open.rocket.chat Gitlab?

**Comment by lolimay** [comment]
> > > how did you test it that it actually works?
> > 
> > 
> > Yes, it works as expected.
> > deepin-screen-recorder_Select area_20190528092411
> 
> Is it working on https://open.rocket.chat Gitlab?

I don't have admin permission of the open.rocket.chat and can't modify the GitLab Url setting option freely.

**Comment by diegolmello** [comment]
@lolimay Forget about admin permission.
Gitlab is working on the web for open server, so it must work on React Native for open server.
If it's working on one, it must work on another.
Otherwise, there's something wrong in your PR.

**Comment by lolimay** [comment]
> @lolimay Forget about admin permission.
> Gitlab is working on the web for open server, so it must work on React Native for open server.
> If it's working on one, it must work on another.
> Otherwise, there's something wrong in your PR.

OK, I understand your concern. How can I do to ensure this patch works for the other open gitlab server? Should I test some of the gitlab open servers and paste the screenshots here? Thanks.

**Comment by diegolmello** [comment]
> > @lolimay Forget about admin permission.
> > Gitlab is working on the web for open server, so it must work on React Native for open server.
> > If it's working on one, it must work on another.
> > Otherwise, there's something wrong in your PR.
> 
> OK, I understand your concern. How can I do to ensure this patch works for the other open gitlab server? Should I test some of the gitlab open servers and paste the screenshots here? Thanks.

It seems you didn't get what the open server is.
When we say "open server", we're referring to https://open.rocket.chat.
Gitlab is configured and it's working.
image

You need to make RN login using Gitlab on our open server.
Forget about "gitlab open servers".

**Comment by lolimay** [comment]
> > > @lolimay Forget about admin permission.
> > > Gitlab is working on the web for open server, so it must work on React Native for open server.
> > > If it's working on one, it must work on another.
> > > Otherwise, there's something wrong in your PR.
> > 
> > 
> > OK, I understand your concern. How can I do to ensure this patch works for the other open gitlab server? Should I test some of the gitlab open servers and paste the screenshots here? Thanks.
> 
> It seems you didn't get what the open server is.
> When we say "open server", we're referring to https://open.rocket.chat.
> Gitlab is configured and it's working.
> image
> 
> You need to make RN login using Gitlab on our open server.
> Forget about "gitlab open servers".

Sorry for the misunderstanding 😅
I’ve tested the patch on my phone. It works with the open server. Please review :)

<kbd>aoaooaoaoao</kbd>

**Pull request merged**
