### PR TITLE
Chore: Migrate UserPreserencesView to Typescript

### PR DESCRIPTION
**Pull request by reinaldonetof**
## How to test or reproduce

- Go to `Profile`, then click on `Preferences` and should open a screen with one button `Notifications` and one Switch button `Enable message Parser`

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by reinaldonetof** [comment]
Authored-by: @FranciscoHeronildo 

Thanks for your contribution, @FranciscoHeronildo! Could you assignee the CLA: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3477#issuecomment-956535177

**Review by AlexAlexandre — APPROVED** [review]
LGTM :)

**Comment by reinaldonetof** [comment]
Hey @FranciscoHeronildo, could you assignee the CLA, pls? Then, we could merge this PR in our branch! Thanks!

**Comment by FranciscoHeronildo** [comment]
> Hey @FranciscoHeronildo, could you assignee the CLA, pls? Then, we could merge this PR in our branch! Thanks!

Done

**Pull request merged**
