### PR TITLE
Feat: Bulgarian & Greek language are now supported

### PR DESCRIPTION
**Pull request by Sumitwarrior7**
## Proposed changes

Under i18n.ts, Bulgarian & Greek language are added

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [X] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Sumitwarrior7** [comment]
WhatsApp Image 2024-01-19 at 11 35 44 AM

**Comment by Sumitwarrior7** [comment]
WhatsApp Image 2024-01-19 at 11 32 47 AM

**Comment by Sumitwarrior7** [comment]
Bulgarian :-

WhatsApp Image 2024-01-19 at 11 35 44 AM

Greek :-

WhatsApp Image 2024-01-19 at 11 38 07 AM

**Comment by Sumitwarrior7** [comment]
Please tell me if any changes are required

**Comment by GleidsonDaniel** [comment]
Where did you get these translations from?

**Comment by Sumitwarrior7** [comment]
> Where did you get these translations from?

Google Translate

**Comment by diegolmello** [comment]
Google Translate isn't enough to be used as localization.

**Comment by Sumitwarrior7** [comment]
> Google Translate isn't enough to be used as localization.

Hello @diegolmello sir, can you please tell me then how can i then verify my translations apart from google translate which can be used for localization

**Pull request closed without merging**
