### PR TITLE
Feat: Add sorting functionality in directory (Implementation of #5423)

### PR DESCRIPTION
**Pull request by preeesha**
## Proposed changes

It was observed that the sorting functionality is missing in the mobile app which was pretty essential from a user's perspective browsing many different entities (Channels, Users & Teams). This PR adds the sorting functionality to the mobile app.

The sorting functionality is added to the `DirectoryView` screen. It features a sort button that opens a modal with the sorting options. The sorting options are `Relevance`, `Ascending`, and `Descending`. The default sorting option is `Relevance`.

The sorting functionality is catered after the search results (the directory) is fetched from the server due to any of the following events:

- The user changes the search query.
- The user changes the sorting option.
- The user changes the search type (Channels, Users & Teams).

Primarily, it uses the entity's name as the sorting criteria. If the entity's name is not available, they are treated on the same level (0 difference, in ref to the JavaScript `sort` function).

## Issue(s)

#5423

## Screenshots
WhatsApp Image 2023-12-27 at 20 39 53_44569a93
WhatsApp Image 2023-12-27 at 20 39 53_ea7de22e

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

Although the current implementation is limited to the sorting based solely on the `name` field, it can be extended to support other fields as well. The `sort` function can be modified to support the sorting based on other fields as well.

> If this pull request is accepted, I would love to be working on adding other sorting options such as `Status`, `Tag`, `Topic`, etc.

### CODE REVIEW

**Comment by brf153** [comment]
@GuptaPrisha Hello Prisha. Actually I have already worked on this issue. I just need to make a commit and push it. I was just travelling back to my college and could not finish the work in time.Please understand that you should first check whether someone else is working or has already worked on this issue before or not. You are simply not respecting the work culture which needs to be followed in the open source community which contributing.

**Comment by GuptaPrisha** [comment]
Hey @diegolmello, I have worked on this issue which adresses the specified concerns. I would really appreciate for you to take a review on the changes I made.

Thank you.

**Comment by GuptaPrisha** [comment]
Hi @brf153,

Thank you for reaching out. I appreciate your efforts in working on the issue. To ensure we align our contributions seamlessly, could you please push your changes to the repository? This way, we can collaboratively review both sets of changes and determine the most effective approach together.

Once your changes are pushed, we can discuss and decide how to best integrate the improvements into the project. I value open communication and collaboration, and I believe our combined efforts will contribute to a stronger solution.

Let me know once your changes are available, and we can coordinate the next steps.

Thanks for your understanding and cooperation.

Best regards,
GuptaPrisha

**Comment by brf153** [comment]
@GuptaPrisha you can check my code #5428

**Comment by brf153** [comment]
We actually need both the sorting of channel as well as user count. I have made the changes for both. You can check my pr it is complete

**Comment by brf153** [comment]
@diegolmello please do check my pr as well #5428

**Comment by GleidsonDaniel** [comment]
There are 90 changed files, correct your PR before requesting review.

**Pull request closed without merging**
