### PR TITLE
[FIX] Deleted thread replies to redirect to Thread

### LINKED ISSUE #2839: [BUG] Deleted thread replies do not redirect to Thread
### Description:

When server setting Message_ShowDeletedStatus is true:
Right now, if you delete a reply to a Thread, the message is deleted but the Thread title awkwardly stays in the roomview. On touching(clicking) this message/thread, nothing happens even though the thread title has an arrow next to it that signals something should indeed happen.

Screenshot_20210127-031314

### Environment Information:

- Rocket.Chat Server Version: 3.11.0-develop
- Rocket.Chat App Version: 4.13.1
- Device Name: Oneplus 6
- OS Version: Android 10

### Steps to reproduce:

1. Reply to a thread.
2. Delete reply.
3. Deleted message in main RoomView. [ Thread preview sits there awkwardly ]

### Expected behavior:

To be redirected to the thread that is mentioned.

### Actual behavior:

Nothing happens

### PR DESCRIPTION
**Pull request by aKn1ghtOut**
## Proposed changes

Modifies the Touchable disabled validation very slightly so that deleted 'system' Thread replies aren't disabled. Hence, all 'system' messages that are connected to a thread and preview on the main roomview should also redirect to the Thread, instead of the Thread being previewed but no feedback on the press.

## Issue(s)	

Closes #2839 

## How to test or reproduce

1. Reply to a thread.
2. Delete reply.
3. Deleted message in main RoomView. [ Thread preview sits there awkwardly ]

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by aKn1ghtOut** [comment]
Realised this might not be the best way to do this.
Will update this PR today accordingly.

**Comment by aKn1ghtOut** [comment]
Just checked and the change does not include any unintended side effects. Please review @diegolmello

**Comment by diegolmello** [comment]
> Just checked and the change does not include any unintended side effects. Please review @diegolmello

Thanks. We'll try to review it by the end of this week.

**Review by diegolmello — APPROVED** [review]
LGTM

**Pull request merged**
