### PR TITLE
Prevent sending empty messages

### PR DESCRIPTION
**Pull request by anirbanpaulcom**
## Proposed changes

This PR prevents sending empty or whitespace-only messages by trimming the message content before send

## Issue(s)	

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/130109852/981ab37b-d28d-4550-80b0-0c35d2cfd82c

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by anirbanpaulcom** [comment]
@diegolmello , @GleidsonDaniel Please take a look. Thank you!

**Comment by anirbanpaulcom** [comment]
@diegolmello , @GleidsonDaniel Please take a look. Thank you!

**Review by diegolmello — DISMISSED** [review]
Hey. Thanks for your contribution! Can you write tests on MessageComposer.test.tsx?

**Comment by anirbanpaulcom** [comment]
> Hey. Thanks for your contribution! Can you write tests on MessageComposer.test.tsx?

Hey @diegolmello, please take a look. Thank you.

**Comment by anirbanpaulcom** [comment]
> Hey. Thanks for your contribution! Can you write tests on MessageComposer.test.tsx?

Hey @diegolmello, please take a look. Thank you.

**Comment by anirbanpaulcom** [comment]
Hey @diegolmello, could you please take a look when you have some time? Thank you!

**Comment by GleidsonDaniel** [comment]
lint is failing

**Comment by anirbanpaulcom** [comment]
> lint is failing

Done, @GleidsonDaniel Please take a look.

**Comment by GleidsonDaniel** [comment]
Update the tests, run the script:
`yarn test -u`

**Comment by anirbanpaulcom** [comment]
> Update the tests, run the script: `yarn test -u`

Done @GleidsonDaniel, Thank you.

**Comment by anirbanpaulcom** [comment]
Hey  @GleidsonDaniel , @diegolmello, could you please take a look when you have some time? Thank you!

**Review by GleidsonDaniel — APPROVED** [review]

**Pull request merged**
