### PR TITLE
[FIX] Initial users' status is not fetched

### PR DESCRIPTION
**Pull request by zaphod534**
## Issue(s)
#2663

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by djorkaeffalexandre — APPROVED** [review]
LGTM, nice catch!
Reproducible steps:
- Just scroll down the rooms list
- It's not requesting user presence again

**Comment by diegolmello** [comment]
@zaphod534 Can you update your branch?
Also, can you tell me if you have `Allow edits by maintainers` checked?
We can't add commit (like updating your branch ourselves) with it unchecked.
Thanks.

**Comment by zaphod534** [comment]
I have updated the PR, now you should be able to merge it.
I tried also to check the `Allow edits by maintainers` option, but I'm not able to do this due [this issue](https://github.com/isaacs/github/issues/1681).

We can add you as contributor to our repo in order to be able to check the option next time.

**Comment by diegolmello** [comment]
> I tried also to check the Allow edits by maintainers option, but I'm not able to do this due this issue.

Awesome. It makes sense now. Thanks!

**Pull request merged**
