### PR TITLE
Arabic

### PR DESCRIPTION
**Pull request by kareemhamdy100**
@RocketChat/ReactNative

arabic
arabic2

### CODE REVIEW

**Comment by diegolmello** [comment]
@kareemhamdy100 Nice job!
I'm having trouble to find someone to review the translation.
I'll review with help from Google Translate anyway, but if you could get some friend of you to help it would be even better.
Thanks.

**Comment by kareemhamdy100** [comment]
> @kareemhamdy100 Nice job!
> I'm having trouble to find someone to review the translation.
> I'll review with help from Google Translate anyway, but if you could get some friend of you to help it would be even better.
> Thanks.

google translate use different meaning  i'll  try to use the app with the arabic and modify what I found 
wrong when I'm sure every thing give the  correct  indication I'll tell you as will

**Comment by diegolmello** [comment]
> > @kareemhamdy100 Nice job!
> > I'm having trouble to find someone to review the translation.
> > I'll review with help from Google Translate anyway, but if you could get some friend of you to help it would be even better.
> > Thanks.
> 
> google translate use different meaning i'll try to use the app with the arabic and modify what I found
> wrong when I'm sure every thing give the correct indication I'll tell you as will

Cool, thanks!

**Comment by HusseinElFeky** [comment]
Some translations are correct; however, there are still many translations that need to be fixed as well as some layout issues like text direction. For reference, you can check [Rocket.Chat.Android](https://github.com/RocketChat/Rocket.Chat.Android) repo. I have added full functionality of Arabic language there, including translation and RTL user interface. You can also install the Android native app if you want to check it.

**Pull request closed without merging**
