### PR TITLE
Add F-Droid logo

### PR DESCRIPTION
**Pull request by licaon-kter**
...but I can't get them to sync the vertical position, where did you get the iOS logo from?

### CODE REVIEW

**Comment by licaon-kter** [comment]
Also, is https://rocket.chat/install hosted somewhere? That needs an update too

**Comment by licaon-kter** [comment]
Any news?

**Comment by diegolmello** [comment]
@licaon-kter Hey. We try to have frequent releases of our mobile apps, but it'd take too long to merge them to F-Droid.
Also we don't have analytics to justify our support.
That's why we stopped maintaining F-Droid for now.

**Comment by licaon-kter** [comment]
Why does it take too long? The cleanup process or the F-Droid build cycle speed?

**Comment by diegolmello** [comment]
@licaon-kter Last time we could not figure out the error happening on CI builds and it took several weeks to have an answer. 2 new releases had happened already.

**Comment by TheLastProject** [comment]
Did you... ever ask? I am not seeing anything on F-Droid's issue tracker asking about a failing build. The only issues I see when I search for "rocket chat" on https://gitlab.com/fdroid/fdroiddata/-/issues?scope=all&state=all&search=rocket+chat I only see issues of the F-Droid team working around proprietary dependencies being added on their own?

**Comment by diegolmello** [comment]
@licaon-kter @TheLastProject Yes, I asked for help here https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7897#note_495329247
That PR was opened Dec 15 2020 and we tried to merge it until Jan 27 2021.
I know there was holidays, but it's still too long.
2 months after my comment I received a reply saying rebase should fix.

I'm not complaining though.
Do you think we should try again?
It'd require some kind of analytics in order to evaluate if it's worth though.

**Comment by TheLastProject** [comment]
Thank you for the link. Yeah, okay, that is suboptimal. While I do believe that generally the F-Droid team is quite responsive, given we're all volunteers this can't truly be prevented.

I personally believe it can be worth it, perhaps not for pure user count but to show a commitment to Open Source (given F-Droid's strict guidelines) as to differentiate Rocket Chat from some of the competition.

One thing I noticed is that the F-Droid build required custom patches and everything. One suggestion I would make is to instead try to have a gradle flavour on your side, so if you need to make some changes like in that MR on F-Droid GitLab you wouldn't depend on the availability of F-Droid contributors and could just make such changes directly here. In that case, as I understand it, the update should've been automatically picked up and built by F-Droid with no issues or delays.

**Comment by diegolmello** [comment]
@licaon-kter @TheLastProject 
> One suggestion I would make is to instead try to have a gradle flavour on your side

That's what we do already. We have `officialFossRelease` build flavor specifically for F-Droid https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7897/diffs#e55300c8ff1349f7cc6f4acd9079452f72338012_240_256
One of the most annoying issues we've had is trying to get our builds passing the linter.
We use React Native, so we have a `node_modules` folder containing proprietary and non-proprietary code.
Our build flavor make sure nothing proprietary is compiled, but that's not enough for the lint, so we need to remove folders from `node_modules` manually. However that triggers yet other issues.

How do you use to deal with React Native projects on F-Droid?

**Comment by licaon-kter** [comment]
`scanignore:` gradle files for deps that are known to be FOSS

**Pull request closed without merging**
