### PR TITLE
feat: adding the sort functionality

### LINKED ISSUE #5423: Feat: Add sorting functionality in directory
### Description:

There is no sorting functionality in the mobile app whereas it is present in the browser and desktop app. I think it will be a good feature to add. 

### Environment Information:

- Rocket.Chat Server Version: 6.5
- Rocket.Chat App Version: 4.45.0.99999999
- Device Name: Samsung Galaxy M13 5G
- OS Version: Ubuntu 22.04
- Android Version: 13

### Steps to reproduce:

1.  Go to the directory in the mobile app as well as the browser.
2.  Notice that there is no sort functionality in the mobile app but it is present there in the browser.

### Expected behavior:

Sorting present in the directory just like in the browser or desktop app 

Screenshot from 2023-12-22 08-26-24

### Actual behavior:

No sorting in the directory

WhatsApp Image 2023-12-22 at 08 30 58

### PR DESCRIPTION
**Pull request by brf153**
## Proposed changes

Adding the sort functionality

## Issue(s)	

closes #5423 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by brf153** [comment]
# Changes till now:

### Added the sort icon

Narrow view:
WhatsApp Image 2023-12-24 at 12 37 29

Wide view:
WhatsApp Image 2023-12-24 at 12 37 05

**Comment by brf153** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/107868772/1fdb89d2-557f-46dc-8f0b-053162722180

**Comment by brf153** [comment]
@diegolmello I have made the changes for issue #5423. I have also added the i18n locales so that it also works after translation

**Comment by brf153** [comment]
## Changes after adding functionalities

WhatsApp Image 2023-12-28 at 01 29 45
WhatsApp Image 2023-12-28 at 01 29 46

**Comment by brf153** [comment]
WhatsApp Image 2023-12-28 at 02 10 30

**Comment by brf153** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/107868772/ccac12b4-c8ed-4d80-a886-72f313464c09

**Comment by brf153** [comment]
Light View:
WhatsApp Image 2023-12-28 at 02 36 22

**Comment by GleidsonDaniel** [comment]
hey @brf153 the link is broken.

**Pull request closed without merging**
