### PR TITLE
[I18N] Add missing italian strings

### PR DESCRIPTION
**Pull request by aenonGit**
Italian translation was missing a lot of strings, this PR adds all the missing ones and fixes some of the existing strings.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by diegolmello** [comment]
Hey, @aenonGit.
I can't update your branch, because you're using a company branch.
Can you do it?
Thanks!

**Comment by aenonGit** [comment]
@diegolmello done!

**Comment by diegolmello** [comment]
Damn, I didn't see this and now it's outdated again.
Do it once more and I'll make sure it's merged.

**Comment by aenonGit** [comment]
np, there you go

**Review by diegolmello — APPROVED** [review]

**Comment by diegolmello** [comment]
@aenonGit Merged. Thank you.

**Pull request merged**
