### PR TITLE
[FIX] Regex typo on markdown

### PR DESCRIPTION
**Pull request by aKn1ghtOut**
## Proposed changes

Just corrected a regex match pattern typo.

## How to test or reproduce

[    ](htps://google.com) does not get removed from message right now, creating an "empty" clickable link. This is because there is a small typo in the regex looking for the empty link patterns. Only single spaces in the link title are matched because of an extra `]`.

### Current regex:
Screenshot from 2021-02-20 22-19-39
Screenshot from 2021-02-20 22-19-55
Even though the text in the second screenshot does not need to be matched.

### After removing extra `]`
Screenshot from 2021-02-20 22-19-26

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by diegolmello** [comment]
@aKn1ghtOut Thanks for your contribution.
Can you add a story on markdown section for this?

**Comment by aKn1ghtOut** [comment]
@diegolmello Added story in markdown section

**Review by kresnaputra — APPROVED** [review]
LGTM

**Review by diegolmello — APPROVED** [review]
@aKn1ghtOut LGTM! 🎉

**Pull request merged**
