### PR TITLE
[NEW] Custom OAuth

### LINKED ISSUE #1018: Support Custom OAuth
**Feature Request**

We'd love to use the new ReactNative client within our project. We're using custom OAuth
to authenticate the users against our own Wordpress. We know it's on your todo list (in `README.md`) but it's the one most far down in the list. 

I kindly suggest to move **Authentication via Custom OAuth** a bit upwards, if the order is the one you're following while implementing. 

For Android, ReactNative is already better than the native Android client. 

- Your Rocket.Chat Experimental app version: 1.15.1
- Your Rocket.Chat server version: 1.1.3
- Device (or Simulator) you're running with: iPhone SE iOS 12

### PR DESCRIPTION
**Pull request by jbuechele**
@RocketChat/ReactNative

Closes #1018

### CODE REVIEW

**Comment by diegolmello** [comment]
@jbuechele Thanks for your work!
Can you fix lint?
I'll review your PR right after.
Cheers.

**Comment by jbuechele** [comment]
The lint errors were fixed.

**Comment by rasos** [comment]
Very useful, looking forward to have this PR in the next release.

**Comment by jbuechele** [comment]
> OAuth

Should I change it or have you already changed it? But we could also just render the icon of oauth or openid connect? Then the buttons would look consistent.

**Comment by jbuechele** [comment]
> Wait, we have a bug!
> 
> Try connection with a different server, then go to the server which supports custom OAuth authentication -> the login "method" list from the first server is being displayed on the second one.

The bug is fixed. The Reducer has merged the old login services with the new ones

**Comment by diegolmello** [comment]
@jbuechele Great job! I'll review/merge it today! :)

**Comment by diegolmello** [comment]
Merged. Thanks, @jbuechele! 👊

**Comment by yeoldegrove** [comment]
@diegolmello Will you bump the version, so that I can download this from google play?

**Comment by diegolmello** [comment]
@yeoldegrove Yes, I'm fixing a few bugs on RN update and I'll release this soon.
First I have to review and merge #1108 and #1116 also.

**Pull request merged**
