### PR TITLE
feat(i18n): add Indian languages

### PR DESCRIPTION
**Pull request by brf153**
## Proposed changes

Added some Indian languages which include Hindi, Bengali, Tamil and Telugu. 

## Screenshots

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/107868772/4df8db62-bced-4bdf-bd85-8b06b5e2eb9e

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by brf153** [comment]
@reinaldonetof sir please review this pr. I have included several widely spoken Indian languages for translation.

**Comment by reinaldonetof** [comment]
Awesome, thanks for the contribution @brf153 

I will check with the team this and how can we review appropriate this!

cc: @diegolmello

**Comment by diegolmello** [comment]
Going to take a look at it soon.

**Comment by brf153** [comment]
@reinaldonetof @diegolmello Looking forward to your review later. Thanks in advance for your time and feedback on my PR!

**Review by diegolmello — APPROVED** [review]

**Comment by brf153** [comment]
@diegolmello you're welcome!

**Pull request merged**
