### PR TITLE
[IMPROVEMENT] User details screen

### LINKED ISSUE #1248: [IMPROVEMENT] User details screen
We should show a user details screen with the user e-mail, timezone and more details (to be checked with the design)

### PR DESCRIPTION
**Pull request by devyaniChoubey**
Added a user details screen
@RocketChat/ReactNative

Closes #1248

Peek 2020-01-25 19-44

### CODE REVIEW

**Comment by devyaniChoubey** [comment]
@diegolmello sir some more info about user should be added or it is fine?

**Comment by diegolmello** [comment]
@devyaniChoubey Nice, thank you!

**Comment by diegolmello** [comment]
Can you resolve conflicts?

**Comment by devyaniChoubey** [comment]
@diegolmello ok sir I will do it.

**Pull request closed without merging**
